Imports

In [227]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Gym Data Importation

In [228]:
data = pd.read_csv('gym_membership.csv', index_col = 0)

Gym Data Exploration

In [229]:
data.head()

,gender,birthday,Age,abonoment_type,visit_per_week,days_per_week,attend_group_lesson,fav_group_lesson,avg_time_check_in,avg_time_check_out,avg_time_in_gym,drink_abo,fav_drink,personal_training,name_personal_trainer,uses_sauna
id,,,,,,,,,,,,,,,,
1,Female,1997-04-18,27,Premium,4,"Mon, Sat, Tue, Wed",True,"Kickboxen, BodyPump, Zumba",19:31:00,21:27:00,116,False,NaN,False,NaN,True
2,Female,1977-09-18,47,Standard,3,"Mon, Sat, Wed",False,NaN,19:31:00,20:19:00,48,False,NaN,True,Chantal,False
3,Male,1983-03-30,41,Premium,1,Sat,True,XCore,08:29:00,10:32:00,123,True,"berry_boost, lemon",True,Mike,False
4,Male,1980-04-12,44,Premium,3,"Sat, Tue, Wed",False,NaN,09:54:00,11:33:00,99,True,passion_fruit,True,Mike,True
5,Male,1980-09-10,44,Standard,2,"Thu, Wed",True,"Running, Yoga, Zumba",08:29:00,09:19:00,50,False,NaN,True,Mike,False

Gym Data information

In [255]:
data.duplicated().sum()

np.int64(0)

In [230]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 1 to 1000
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   gender                 1000 non-null   object
 1   birthday               1000 non-null   object
 2   Age                    1000 non-null   int64
 3   abonoment_type         1000 non-null   object
 4   visit_per_week         1000 non-null   int64
 5   days_per_week          1000 non-null   object
 6   attend_group_lesson    1000 non-null   bool
 7   fav_group_lesson       503 non-null    object
 8   avg_time_check_in      1000 non-null   object
 9   avg_time_check_out     1000 non-null   object
 10  avg_time_in_gym        1000 non-null   int64
 11  drink_abo              1000 non-null   bool
 12  fav_drink              496 non-null    object
 13  personal_training      1000 non-null   bool
 14  name_personal_trainer  518 non-null    object
 15  uses_sauna             1000 non-null   bool
dtypes: bool(4), int64(3), object(9)
memory usage: 105.5+ KB

In [231]:
data.describe()

               Age  visit_per_week  avg_time_in_gym
count  1000.000000     1000.000000      1000.000000
mean     30.604000        2.682000       105.260000
std      10.817958        1.241941        43.557177
min      12.000000        1.000000        30.000000
25%      21.000000        2.000000        67.000000
50%      30.000000        3.000000       104.000000
75%      40.000000        3.000000       143.000000
max      49.000000        5.000000       180.000000

Notes in which we have to transform this variables into:

- Gender - (0/1) , 1 as Male, 0 as Female
- Birthday - Encoding by generations
- Age - Drop (Redundande with the birthday)
- Subscription type - (0/1) , 1 as Premium, 0 as Standard
- Number of visits per week - Equal
- Which days on the week - Enconding
- Attend group lessons - Drop (Next columns will say if the client attend group lessons)
- Favortite group lesson - Encoding
- Average time check in - Encoding
- Average time check out - Drop (Redundance since we have the check in and average time in the gym)
- Average time in the gym - Equal
- Drink or not during the workout - Drop (Next columns will say if the client drinks something)
- Favorite drink - Encoding
- Has a personal trainer - Drop (Next columns will say if the client has a personal trainer)
- Name of the personal trainer - Encoding
- Uses sauna - (0/1) , 1 being 'Yes', 0 being 'No'

New and Clean Dataset (Improved)

In [232]:
improved = pd.DataFrame()

Gender

In [233]:
improved['Gender'] = data['gender'].map({'Male': 1, 'Female': 0})

Generation

- Baby Boomers: start 1946

- Generation X: start 1965

- Millennials (Generation Y): start 1981

- Generation Z: start 1997

- Generation Alpha: start 2010

- Generation Beta: start 2025 (projected)

In [234]:
improved['Baby Boomers'] = data['birthday'].dropna().apply(lambda i: 1 if int(i.split('-')[0]) >= 1946 and int(i.split('-')[0]) <= 1964 else 0)
improved['Generation X'] = data['birthday'].dropna().apply(lambda i: 1 if int(i.split('-')[0]) >= 1965 and int(i.split('-')[0]) <= 1980 else 0)
improved['Millennials'] = data['birthday'].dropna().apply(lambda i: 1 if int(i.split('-')[0]) >= 1981 and int(i.split('-')[0]) <= 1996 else 0)
improved['Generation Z'] = data['birthday'].dropna().apply(lambda i: 1 if int(i.split('-')[0]) >= 1997 and int(i.split('-')[0]) <= 2012 else 0)
improved['Generation Alpha'] = data['birthday'].dropna().apply(lambda i: 1 if int(i.split('-')[0]) >= 2013 else 0)

Subscription

In [235]:
improved['Subscription'] = data['abonoment_type'].map({'Premium': 1, 'Standard': 0})

Number of Visits per Week

In [236]:
improved['Number of Visits per Week'] = data['visit_per_week']

Which days of the week the client goes to the gym

In [237]:
days_of_the_week = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']

for day in days_of_the_week:
    improved[day] = data['days_per_week'].str.contains(day, case=False, na=False).astype(int)

Which class the client attends

🥊 High Intensity

- Kickboxen
- XCore
- HIT

💃 Dance / Rhythm

- Zumba
- LesMiles

🏋️ Strength / Conditioning

- BodyPump
- Spinning

🧘 Mind / Body

- Yoga
- BodyBalance
- Pilates

🏃 Cardio

- Running

In [238]:
improved['High Intensity'] = 0
improved['Dance/Rhythm'] = 0
improved['Strength/Conditioning'] = 0
improved['Mind/Body'] = 0
improved['Cardio'] = 0

In [239]:
high_intensity = ['Kickboxen', 'XCore', 'HIT']
dance          = ['Zumba', 'LesMiles']
strength       = ['BodyPump', 'Spinning']
mind_body      = ['Yoga', 'BodyBalance', 'Pilates']
cardio         = ['Running']

for i in data.index:
    
    if pd.isna(data.loc[i,'fav_group_lesson']):
        continue
    
    lessons = [x.strip() for x in data.loc[i, 'fav_group_lesson'].split(',')]

    for lesson in lessons:
        if lesson in high_intensity:
            improved.loc[i, 'High Intensity'] = 1
        if lesson in dance:
            improved.loc[i, 'Dance/Rhythm'] = 1
        if lesson in strength:
            improved.loc[i, 'Strength/Conditioning'] = 1
        if lesson in mind_body:
            improved.loc[i, 'Mind/Body'] = 1
        if lesson in cardio:
            improved.loc[i, 'Cardio'] = 1

Average time the client checks in

In [240]:
data['avg_time_check_in'] = data['avg_time_check_in'].astype('datetime64[ns]')
data['avg_time_check_out'] = data['avg_time_check_out'].astype('datetime64[ns]')

In [241]:
hours = data['avg_time_check_in'].dt.hour

improved['Morning'] = ((hours >= 0) & (hours < 12)).astype(int)
improved['Afternoon'] = ((hours >= 12) & (hours < 17)).astype(int)
improved['Evening'] = ((hours >= 17) & (hours < 24)).astype(int)

Average workout duration

In [242]:
improved['Average Workout Duration'] = data['avg_time_in_gym']

If the client drinks something during the workout and which

In [243]:
improved['Berry Boost'] = 0
improved['Lemon'] = 0
improved['Passion Fruit'] = 0
improved['Coconut Pineapple'] = 0
improved['Orange'] = 0
improved['Black Currant'] = 0

In [244]:
flavours = ['berry_boost', 'lemon', 'passion_fruit', 'coconut_pineapple', 'orange', 'black_currant']

for i in data.index:
    
    if pd.isna(data.loc[i, 'fav_drink']):
        continue

    drinks = [x.strip() for x in data.loc[i, 'fav_drink'].split(',')]
              
    if 'berry_boost' in drinks:
        improved.loc[i, 'Berry Boost'] = 1
    if 'lemon' in drinks:
        improved.loc[i, 'Lemon'] = 1
    if 'passion_fruit' in drinks:
        improved.loc[i, 'Passion Fruit'] = 1
    if 'coconut_pineapple' in drinks:
        improved.loc[i, 'Coconut Pineapple'] = 1
    if 'orange' in drinks:
        improved.loc[i, 'Orange'] = 1
    if 'black_currant' in drinks:
        improved.loc[i, 'Black Currant'] = 1

If the client has personal trainer and which

In [245]:
improved['Chantal'] = 0
improved['Mike'] = 0
improved['Jeffrey'] = 0
improved['Hanna'] = 0

In [246]:
names = ['Chantal', 'Mike', 'Jeffrey', 'Hanna']

for i in data.index:
    if pd.isna(data.loc[i, 'name_personal_trainer']):
        continue

    for name in names:
        if name in data.loc[i, 'name_personal_trainer']:
            improved.loc[i, name] = 1

If the client uses the sauna

In [247]:
improved['Sauna'] = data['uses_sauna'].map({True: 1, False: 0})

Save some space

In [249]:
for i in improved.columns:
    if i == 'Average Workout Duration':
        improved[i] = improved[i].astype('Int16')
    if i == 'Number of Visits per Week':
        improved[i] = improved[i].astype('Int16')
    

    improved[i] = improved[i].astype('Int8')

Improved dataset information

In [250]:
improved.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 1 to 1000
Data columns (total 35 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Gender                     1000 non-null   Int8
 1   Baby Boomers               1000 non-null   Int8
 2   Generation X               1000 non-null   Int8
 3   Millennials                1000 non-null   Int8
 4   Generation Z               1000 non-null   Int8
 5   Generation Alpha           1000 non-null   Int8
 6   Subscription               1000 non-null   Int8
 7   Number of Visits per Week  1000 non-null   Int8
 8   Mon                        1000 non-null   Int8
 9   Tue                        1000 non-null   Int8
 10  Wed                        1000 non-null   Int8
 11  Thu                        1000 non-null   Int8
 12  Fri                        1000 non-null   Int8
 13  Sat                        1000 non-null   Int8
 14  Sun                        1000 non-null   Int8
 15  High Intensity             1000 non-null   Int8
 16  Dance/Rhythm               1000 non-null   Int8
 17  Strength/Conditioning      1000 non-null   Int8
 18  Mind/Body                  1000 non-null   Int8
 19  Cardio                     1000 non-null   Int8
 20  Morning                    1000 non-null   Int8
 21  Afternoon                  1000 non-null   Int8
 22  Evening                    1000 non-null   Int8
 23  Average Workout Duration   1000 non-null   Int8
 24  Berry Boost                1000 non-null   Int8
 25  Lemon                      1000 non-null   Int8
 26  Passion Fruit              1000 non-null   Int8
 27  Coconut Pineapple          1000 non-null   Int8
 28  Orange                     1000 non-null   Int8
 29  Black Currant              1000 non-null   Int8
 30  Chantal                    1000 non-null   Int8
 31  Mike                       1000 non-null   Int8
 32  Jeffrey                    1000 non-null   Int8
 33  Hanna                      1000 non-null   Int8
 34  Sauna                      1000 non-null   Int8
dtypes: Int8(35)
memory usage: 108.5 KB

In [254]:
improved.describe()

,Gender,Baby Boomers,Generation X,Millennials,Generation Z,Generation Alpha,Subscription,Number of Visits per Week,Mon,Tue,...,Lemon,Passion Fruit,Coconut Pineapple,Orange,Black Currant,Chantal,Mike,Jeffrey,Hanna,Sauna
count,1000.0,1000.0,1000.0,1000.0,1000.0,1000.0,1000.0,1000.0,1000.0,1000.0,...,1000.0,1000.0,1000.0,1000.0,1000.0,1000.0,1000.0,1000.0,1000.0,1000.0
mean,0.497,0.0,0.16,0.419,0.421,0.0,0.493,2.682,0.349,0.391,...,0.115,0.119,0.134,0.126,0.111,0.153,0.14,0.111,0.114,0.493
std,0.500241,0.0,0.366789,0.493642,0.493967,0.0,0.500201,1.241941,0.476892,0.488219,...,0.319182,0.323951,0.340823,0.332015,0.314289,0.360168,0.347161,0.314289,0.31797,0.500201
min,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75%,1.0,0.0,0.0,1.0,1.0,0.0,1.0,3.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
max,1.0,0.0,1.0,1.0,1.0,0.0,1.0,5.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

Check if we have any missing values

In [251]:
improved.isnull().any().any()  # False = no missing values anywhere

np.False_

In [256]:
improved.to_csv('clean_gym_membership.csv', index=False)

In [252]:
lst = (data['birthday']
       .dropna()
       .astype(str)
       .str.split(',')
       .explode()
       .str.strip()
       .unique()
       .tolist())

In [253]:
lst

['1997-04-18',
 '1977-09-18',
 '1983-03-30',
 '1980-04-12',
 '1980-09-10',
 '2009-06-29',
 '1994-08-07',
 '2003-11-13',
 '1978-07-28',
 '2000-05-06',
 '1983-07-11',
 '1997-09-19',
 '1994-04-22',
 '1989-03-21',
 '1989-10-01',
 '1987-12-20',
 '1986-12-17',
 '2011-04-30',
 '1986-05-29',
 '1991-09-13',
 '1997-12-31',
 '1997-10-29',
 '2010-10-22',
 '2010-01-24',
 '2008-10-04',
 '1989-06-17',
 '2005-03-31',
 '1992-04-10',
 '1997-01-21',
 '2002-11-04',
 '1988-03-04',
 '2000-03-02',
 '1982-02-26',
 '1976-12-07',
 '2004-03-06',
 '1990-03-09',
 '1981-03-18',
 '1983-11-01',
 '1980-07-05',
 '2006-01-19',
 '2008-06-11',
 '1989-07-08',
 '1995-06-26',
 '1996-04-05',
 '1976-01-19',
 '1981-05-22',
 '1989-03-04',
 '1997-11-15',
 '1975-10-23',
 '1979-12-29',
 '1979-07-17',
 '1996-04-21',
 '2004-07-17',
 '1980-11-27',
 '2000-01-04',
 '2002-07-26',
 '2001-06-12',
 '1977-12-30',
 '2007-07-11',
 '1988-08-20',
 '1977-05-08',
 '1995-05-13',
 '1994-03-10',
 '2002-05-16',
 '1982-11-21',
 '1979-03-27',
 '2002-04-26',
 '2004-07-16',
 '1990-12-12',
 '1988-08-01',
 '1994-09-21',
 '2007-03-13',
 '1988-12-31',
 '1995-12-16',
 '1996-11-30',
 '2004-06-09',
 '2007-04-19',
 '1990-10-24',
 '1981-04-24',
 '1988-09-23',
 '1978-10-15',
 '1981-11-06',
 '1995-04-02',
 '2006-07-30',
 '1992-04-27',
 '1997-02-09',
 '1977-06-27',
 '2008-10-05',
 '1984-12-21',
 '1978-08-24',
 '2003-03-08',
 '1993-08-17',
 '1984-06-06',
 '1983-06-03',
 '2012-05-10',
 '1984-04-10',
 '1995-03-24',
 '2005-09-18',
 '1990-03-23',
 '2003-02-08',
 '1980-05-18',
 '2000-02-15',
 '1990-11-06',
 '1976-12-20',
 '1986-03-15',
 '2012-08-28',
 '2003-07-22',
 '2002-03-05',
 '1991-03-27',
 '2004-03-01',
 '1994-02-01',
 '2009-03-06',
 '1977-07-31',
 '1994-06-18',
 '2010-09-16',
 '1991-03-17',
 '1975-04-04',
 '1983-12-28',
 '1978-07-07',
 '1984-05-06',
 '2002-03-30',
 '1981-07-02',
 '1990-10-28',
 '2010-07-29',
 '2010-04-20',
 '2009-10-16',
 '2004-12-16',
 '1992-02-27',
 '1977-03-30',
 '1981-05-27',
 '1989-11-17',
 '2003-03-19',
 '1997-04-26',
 '1993-08-20',
 '2003-05-19',
 '2009-06-30',
 '2004-09-18',
 '1988-04-10',
 '1993-04-07',
 '2010-02-25',
 '1984-05-28',
 '2002-03-07',
 '2008-03-19',
 '1975-03-11',
 '2010-06-21',
 '2010-08-20',
 '1988-03-17',
 '1988-03-22',
 '1998-06-29',
 '2005-06-27',
 '1995-02-02',
 '1997-09-25',
 '1977-07-22',
 '1985-03-16',
 '1977-08-27',
 '2004-02-01',
 '2004-08-30',
 '2002-02-02',
 '2002-06-03',
 '2000-03-19',
 '2006-12-22',
 '1995-01-27',
 '1987-11-24',
 '2004-01-29',
 '1995-05-22',
 '1992-09-19',
 '1981-10-15',
 '2010-10-05',
 '1988-11-28',
 '1981-07-29',
 '1987-08-22',
 '1975-07-05',
 '1977-07-27',
 '1975-03-17',
 '2005-09-22',
 '1976-02-24',
 '2001-01-29',
 '2000-11-18',
 '2010-11-25',
 '1976-06-20',
 '1996-12-20',
 '2010-02-16',
 '2010-07-14',
 '2006-10-16',
 '1985-09-18',
 '1975-03-24',
 '2012-04-17',
 '1987-02-28',
 '1987-11-12',
 '2011-09-08',
 '1992-10-23',
 '1985-07-11',
 '2012-06-09',
 '2001-08-15',
 '1979-04-24',
 '1985-02-09',
 '2010-03-26',
 '1994-08-05',
 '2009-01-06',
 '2012-08-31',
 '1978-09-29',
 '1975-05-25',
 '1980-12-20',
 '2005-02-18',
 '1982-05-29',
 '1978-03-21',
 '2006-06-20',
 '1983-01-02',
 '2005-09-11',
 '2007-08-21',
 '1997-03-26',
 '1999-01-22',
 '2001-07-18',
 '1989-01-01',
 '1985-12-14',
 '1975-04-11',
 '1990-06-16',
 '1978-01-12',
 '1979-06-18',
 '1979-03-05',
 '1975-04-08',
 '2005-10-05',
 '2000-07-30',
 '2000-09-30',
 '1993-07-30',
 '1976-10-01',
 '2007-03-05',
 '1993-03-26',
 '2001-10-22',
 '1986-11-23',
 '1985-08-24',
 '2010-09-29',
 '2005-09-10',
 '1997-07-21',
 '1989-04-08',
 '2005-01-09',
 '2003-06-25',
 '2003-10-27',
 '2005-01-03',
 '1981-10-31',
 '2006-08-02',
 '1975-08-16',
 '2007-10-11',
 '1997-08-06',
 '2000-09-17',
 '1987-04-19',
 '2000-08-17',
 '1995-11-14',
 '2006-08-27',
 '2006-06-21',
 '1992-05-28',
 '1983-10-27',
 '2003-04-14',
 '1985-12-18',
 '1979-03-28',
 '2001-12-21',
 '2007-05-08',
 '1992-05-24',
 '1980-10-02',
 '1977-05-27',
 '1981-03-19',
 '1976-07-05',
 '1992-07-30',
 '1987-02-06',
 '1988-05-12',
 '2001-12-03',
 '1987-10-07',
 '1985-03-01',
 '1976-12-28',
 '1975-01-12',
 '1996-12-27',
 '1980-04-03',
 '2011-06-09',
 '2010-04-02',
 '1999-04-25',
 '1992-02-03',
 '1994-10-15',
 '1983-01-24',
 '2003-06-01',
 '1999-07-06',
 '2002-12-16',
 '2010-12-21',
 '1976-06-08',
 '2004-01-23',
 '1982-06-12',
 '2004-04-19',
 '1998-05-05',
 '1982-04-24',
 '2007-07-26',
 '1998-05-04',
 '1983-09-02',
 '1988-10-09',
 '2000-12-30',
 '1994-05-09',
 '1990-04-09',
 '1981-03-27',
 '2011-07-09',
 '2001-04-14',
 '1979-01-03',
 '1982-01-23',
 '1988-12-28',
 '1998-08-02',
 '2003-10-28',
 '1992-04-06',
 '1993-07-02',
 '1995-06-28',
 '1990-02-08',
 '1980-07-20',
 '1975-12-28',
 '1988-03-06',
 '2008-02-29',
 '2009-12-28',
 '1988-09-27',
 '1984-05-18',
 '1992-06-01',
 '2012-01-23',
 '1998-04-22',
 '2000-11-03',
 '1998-06-19',
 '1994-07-14',
 '1995-02-19',
 '1977-07-03',
 '2011-09-21',
 '2002-09-30',
 '1991-06-30',
 '1997-08-13',
 '1989-08-06',
 '2003-02-22',
 '1984-06-13',
 '2009-07-02',
 '2000-11-21',
 '1975-03-02',
 '1982-04-13',
 '1997-10-04',
 '1983-09-04',
 '2002-03-22',
 '1988-05-16',
 '1998-08-11',
 '2005-10-07',
 '1986-10-10',
 '1985-08-18',
 '1981-07-18',
 '1985-10-08',
 '2003-07-02',
 '1985-06-18',
 '1988-11-21',
 '1988-10-30',
 '1993-03-02',
 '2009-05-31',
 '1980-06-05',
 '1987-02-13',
 '1992-05-13',
 '2007-09-16',
 '1987-07-27',
 '1999-02-05',
 '1992-05-02',
 '1980-05-14',
 '1987-06-28',
 '2007-02-25',
 '1990-06-27',
 '2003-09-24',
 '1980-06-04',
 '1996-02-26',
 '2001-07-09',
 '1995-05-09',
 '1996-01-05',
 '2003-05-25',
 '1978-10-10',
 '1991-08-26',
 '1984-12-16',
 '1998-12-14',
 '1995-07-29',
 '1990-10-13',
 '1984-08-22',
 '2010-03-07',
 '1981-06-02',
 '1998-07-25',
 '1978-12-06',
 '1998-08-28',
 '1998-06-12',
 '2008-01-12',
 '1975-06-09',
 '1998-09-03',
 '2005-03-17',
 '1990-06-11',
 '2012-09-12',
 '1998-02-06',
 '1985-05-18',
 '1983-08-28',
 '2007-05-14',
 '1995-10-27',
 '1986-11-13',
 '1991-06-18',
 '1979-06-28',
 '2007-03-09',
 '1994-11-14',
 '2004-10-11',
 '2007-06-21',
 '2007-12-04',
 '2009-08-09',
 '1997-04-05',
 '1998-06-11',
 '2002-09-28',
 '2001-12-23',
 '2004-12-19',
 '1979-04-01',
 '1980-08-27',
 '1984-12-09',
 '1993-10-26',
 '1995-01-01',
 '1994-12-26',
 '1988-01-12',
 '2007-11-02',
 '1975-09-25',
 '2004-11-26',
 '1978-02-27',
 '1998-01-09',
 '1990-05-21',
 '1987-04-18',
 '2002-04-02',
 '1983-05-03',
 '1985-07-09',
 '2010-05-02',
 '2008-07-22',
 '1993-04-19',
 '1998-12-06',
 '1993-07-16',
 '1994-01-10',
 '1977-01-28',
 '1995-04-29',
 '1981-04-20',
 '2001-05-02',
 '1997-08-23',
 '1990-02-22',
 '2011-12-20',
 '1987-09-27',
 '1986-03-24',
 '1994-05-17',
 '1998-11-11',
 '1975-02-23',
 '1989-04-11',
 '1982-12-05',
 '1991-04-09',
 '1997-07-13',
 '2006-07-23',
 '2006-06-24',
 '1994-04-09',
 '1985-06-16',
 '1994-03-25',
 '1999-01-10',
 '2008-05-19',
 '1993-12-26',
 '1983-03-19',
 '1986-02-14',
 '1978-03-02',
 '1995-12-20',
 '2009-06-23',
 '1999-06-01',
 '2006-04-22',
 '1986-09-20',
 '2001-10-29',
 '1980-01-13',
 '2010-01-27',
 '1983-01-28',
 '1990-06-21',
 '1998-10-07',
 '1976-04-23',
 '1979-01-02',
 '2003-11-18',
 '1991-08-03',
 '2001-04-04',
 '2002-03-09',
 '1980-10-31',
 '2010-03-23',
 '2000-07-25',
 '1979-03-26',
 '2005-07-27',
 '1998-03-17',
 '1996-05-03',
 '1979-03-31',
 '1975-09-16',
 '1998-02-22',
 '1981-04-25',
 '1991-10-08',
 '1996-06-14',
 '1975-07-18',
 '2007-11-19',
 '1984-11-15',
 '2012-07-22',
 '1984-03-30',
 '1979-12-03',
 '2012-09-19',
 '1981-08-07',
 '1995-09-22',
 '2005-10-14',
 '2005-03-14',
 '2010-11-29',
 '2007-10-19',
 '2000-12-01',
 '1989-05-02',
 '1997-07-09',
 '1977-05-24',
 '1979-09-18',
 '1997-03-21',
 '2005-03-23',
 '1988-01-16',
 '2000-12-23',
 '1999-05-03',
 '2001-05-13',
 '2002-10-23',
 '1975-10-30',
 '2007-06-28',
 '2010-11-26',
 '1991-09-12',
 '1993-03-01',
 '2000-03-03',
 '1994-01-12',
 '2009-07-17',
 '1997-04-07',
 '2008-01-07',
 '1990-08-20',
 '1998-07-30',
 '2004-09-13',
 '1979-04-17',
 '1993-06-10',
 '1976-09-28',
 '1985-08-29',
 '1996-01-31',
 '2006-09-25',
 '1988-03-25',
 '1997-12-18',
 '1980-06-26',
 '2012-08-18',
 '2000-02-12',
 '1976-09-04',
 '2011-10-11',
 '1995-08-03',
 '2012-09-21',
 '1987-06-02',
 '2003-11-04',
 '2002-09-08',
 '2011-05-04',
 '1989-07-31',
 '2006-08-31',
 '1988-09-21',
 '1986-11-05',
 '1986-12-14',
 '1978-01-19',
 '1985-05-27',
 '1985-04-20',
 '1987-03-26',
 '1975-11-26',
 '1978-08-08',
 '1979-07-13',
 '1981-09-23',
 '1986-10-09',
 '2008-06-20',
 '2007-03-15',
 '1982-03-19',
 '1991-07-05',
 '1979-11-24',
 '1989-08-26',
 '1993-07-21',
 '1983-11-16',
 '1975-04-20',
 '2008-07-26',
 '1997-04-19',
 '1975-03-30',
 '1991-03-09',
 '2008-06-10',
 '2002-11-24',
 '1983-04-02',
 '1988-10-22',
 '2006-07-29',
 '1975-09-09',
 '1980-08-22',
 '1994-01-26',
 '1995-10-21',
 '1997-11-09',
 '1991-11-13',
 '1998-03-16',
 '2004-12-08',
 '2009-06-28',
 '1993-08-29',
 '1984-10-22',
 '1980-11-21',
 '1998-07-23',
 '2009-05-04',
 '1991-05-13',
 '1978-07-25',
 '1975-12-22',
 '2009-11-05',
 '1985-11-28',
 '1979-10-17',
 '1984-11-19',
 '1975-04-28',
 '2007-04-03',
 '1989-02-20',
 '1979-02-18',
 '1995-02-23',
 '1982-09-29',
 '2006-05-09',
 '1988-05-20',
 '1990-07-20',
 '1987-12-04',
 '1979-05-08',
 '1981-07-25',
 '2008-08-09',
 '1985-06-28',
 '1987-09-01',
 '2000-01-17',
 '1986-10-27',
 '1976-01-20',
 '2000-04-22',
 '1983-10-10',
 '1976-04-24',
 '2011-03-26',
 '1980-10-30',
 '2002-10-07',
 '2003-10-02',
 '1995-06-19',
 '1985-02-07',
 '2007-08-08',
 '2003-07-25',
 '1996-03-05',
 '1987-03-27',
 '1997-10-13',
 '1999-12-22',
 '2005-12-03',
 '1998-01-07',
 '2001-06-15',
 '2005-11-02',
 '1999-10-07',
 '2007-04-06',
 '1999-08-17',
 '1976-11-06',
 '1999-07-25',
 '2010-07-16',
 '2010-10-02',
 '2000-07-26',
 '1998-09-22',
 '2002-05-28',
 '2012-09-15',
 '2010-09-13',
 '2006-08-22',
 '1997-10-25',
 '1978-01-01',
 '1996-07-22',
 '2011-09-24',
 '1984-06-15',
 '1999-01-01',
 '2006-10-15',
 '1977-06-17',
 '2009-12-05',
 '1985-12-07',
 '1992-10-12',
 '2011-03-27',
 '1982-11-23',
 '1976-03-12',
 '1988-11-30',
 '1985-04-07',
 '2001-01-16',
 '1985-06-11',
 '1977-01-08',
 '2009-11-17',
 '2010-04-14',
 '1983-02-26',
 '1980-06-13',
 '2000-05-16',
 '1984-11-21',
 '1987-01-11',
 '1999-08-20',
 '1986-11-21',
 '1989-10-27',
 '1975-06-05',
 '2005-12-25',
 '1981-08-15',
 '1994-05-04',
 '2011-08-05',
 '2011-05-02',
 '1979-08-28',
 '1996-05-06',
 '2007-11-30',
 '1987-12-14',
 '2005-01-29',
 '1997-07-24',
 '2000-08-02',
 '2002-03-11',
 '1975-03-21',
 '2009-05-06',
 '1988-12-13',
 '2000-10-14',
 '1983-09-05',
 '1988-06-18',
 '1989-02-16',
 '1991-11-30',
 '1985-06-13',
 '1996-06-16',
 '1983-11-25',
 '2005-08-19',
 '1983-03-20',
 '1999-12-08',
 '1986-11-06',
 '1981-08-19',
 '1981-06-06',
 '1995-08-02',
 '1980-02-07',
 '1996-11-28',
 '1990-01-20',
 '2006-02-17',
 '1994-07-29',
 '2005-06-12',
 '1997-09-03',
 '1977-07-15',
 '1982-10-12',
 '1990-06-17',
 '1985-06-06',
 '2001-03-17',
 '1985-07-10',
 '2008-05-24',
 '1991-06-20',
 '1977-01-24',
 '1991-02-05',
 '1982-12-16',
 '1988-03-16',
 '2003-11-09',
 '2005-06-25',
 '2009-04-06',
 '1997-08-27',
 '1992-12-08',
 '2004-10-02',
 '2011-05-01',
 '2007-08-01',
 '1980-10-25',
 '1981-09-01',
 '2012-07-21',
 '1975-04-26',
 '1991-07-02',
 '1995-10-30',
 '1990-12-09',
 '2008-05-08',
 '1983-05-09',
 '2003-12-30',
 '1997-11-05',
 '2005-08-10',
 '1981-05-15',
 '1983-08-20',
 '1978-11-22',
 '2009-10-22',
 '1978-03-17',
 '1989-07-13',
 '1995-07-31',
 '1997-09-01',
 '1988-06-27',
 '1995-01-30',
 '1988-06-26',
 '1988-04-18',
 '2012-03-09',
 '1980-04-18',
 '1978-05-27',
 '1987-09-14',
 '2000-01-21',
 '1978-02-28',
 '2004-01-12',
 '1991-12-16',
 '1997-11-22',
 '1985-10-16',
 '1979-09-19',
 '2003-11-17',
 '1976-04-13',
 '1982-11-16',
 '1999-12-27',
 '1977-06-26',
 '1982-05-14',
 '1990-10-16',
 '2000-04-19',
 '1995-02-18',
 '1994-10-06',
 '1978-01-21',
 '1988-03-02',
 '1995-08-12',
 '1990-08-27',
 '1977-07-23',
 '1997-11-10',
 '1983-07-06',
 '2006-05-20',
 '1976-06-04',
 '1999-07-20',
 '1997-05-05',
 '1989-11-20',
 '1994-09-24',
 '1994-03-19',
 '2005-06-15',
 '1975-06-22',
 '1996-12-13',
 '1986-08-06',
 '1977-05-28',
 '1985-08-31',
 '2006-12-16',
 '2003-11-14',
 '2009-07-13',
 '1986-08-18',
 '1975-10-11',
 '1995-10-19',
 '1986-07-21',
 '1975-07-30',
 '1992-02-26',
 '2006-02-28',
 '2006-03-31',
 '1984-06-21',
 '1982-03-30',
 '1996-09-27',
 '2008-07-27',
 '1999-11-22',
 '2010-03-28',
 '2003-11-08',
 '1983-09-20',
 '2000-12-24',
 '1975-07-29',
 '1978-12-24',
 '1975-11-12',
 '1995-09-16',
 '1993-04-29',
 '1995-03-12',
 '1981-10-11',
 '1995-01-05',
 '1979-01-14',
 '1994-11-10',
 '2000-06-20',
 '1985-04-18',
 '1991-03-21',
 '2007-08-23',
 '1989-08-17',
 '1985-07-13',
 '1998-10-29',
 '2010-03-21',
 '1984-09-05',
 '1999-04-06',
 '1988-01-30',
 '1999-12-16',
 '1993-01-02',
 '1992-09-03',
 '1976-09-24',
 '1979-03-18',
 '2002-07-10',
 '1984-12-08',
 '1979-02-03',
 '2007-04-29',
 '1989-10-13',
 '1991-07-09',
 '2010-07-23',
 '1984-05-26',
 '2001-08-21',
 '2010-01-16',
 '2012-01-17',
 '2009-05-07',
 '2002-12-22',
 '1995-02-05',
 '2000-09-22',
 '1995-04-14',
 '2010-10-04',
 '1975-06-21',
 '1987-08-04',
 '2005-03-20',
 '2000-10-24',
 '1990-07-19',
 '2006-02-23',
 '1997-08-28',
 '1977-09-19',
 '1993-11-25',
 '1984-09-13',
 '2004-03-21',
 '1988-06-14',
 '1987-11-06',
 '1987-10-27',
 '2008-03-27',
 '2000-07-08',
 '1988-05-27',
 '1984-01-14',
 '1984-03-14',
 '2010-01-10',
 '1991-08-29',
 '1981-09-22',
 '1976-07-28',
 '2012-03-22',
 '1985-01-23',
 '1994-09-05',
 '2000-06-07',
 '1977-08-19',
 '1989-11-26',
 '1994-06-02',
 '2001-04-12',
 '2000-08-14',
 '2011-06-28',
 '2006-05-28',
 '1979-07-23',
 '1983-02-20',
 '2011-02-04',
 '1989-11-29',
 '1981-09-05',
 '1985-05-11',
 '2011-08-16',
 '2001-11-09',
 '2001-03-13',
 '1987-09-17',
 '1994-11-07',
 '2001-09-20',
 '1997-03-28',
 '2009-07-08',
 '1983-02-25',
 '2009-05-29',
 '2010-12-06',
 '1975-08-05',
 '1992-10-11',
 '1981-10-08',
 '1991-06-21',
 '1978-12-21',
 '1981-03-08',
 '1984-02-22',
 '1993-09-29',
 '1975-11-29',
 '2003-02-14',
 '2006-07-10',
 '2000-03-27',
 '1990-07-08',
 '2001-10-31',
 '2002-11-03',
 '1982-03-09',
 '1977-06-25',
 '1979-12-10',
 '1986-01-23',
 '2010-08-27',
 '2005-07-14',
 '2010-03-25',
 '2003-04-12',
 '1993-02-23',
 '1990-12-24',
 '1995-12-21',
 '2011-03-17',
 '1981-04-27',
 '2009-11-01',
 '1988-02-23',
 '1998-03-25',
 '2011-05-25',
 '1998-11-12',
 '1978-05-19',
 '2002-01-24',
 '1993-11-21',
 '1991-03-18',
 '1995-11-13',
 '1976-10-08',
 '2008-10-13',
 '2000-10-06',
 '2008-05-02',
 '1992-05-18',
 '1992-01-22',
 '2003-08-21',
 '1987-10-03',
 '1975-10-12',
 '1981-12-16',
 '1979-03-14',
 '1977-07-29',
 '1990-01-29',
 '1997-10-07',
 '1981-04-01',
 '1991-08-12',
 '1985-10-02',
 '2007-01-29',
 '1988-03-23',
 '1984-09-22',
 '2008-11-19',
 '1984-10-05',
 '2001-02-22',
 '2006-05-07']